backtest_settings:
    start_date: '2021-01-01'
    end_date: '2025-01-01'
    initial_cash: 100000.0
    benchmark_ticker: 'SPY'
    top_n_positions: 5
    take_profit:
        type: 'indicator'
        strategy: 'RsiExit'
        params:
            rsi_period: 14
            sell_threshold: 80 # Sell to take profit when RSI is over 75.

    # --- Stop-Loss based on a fixed percentage ---
    # This acts as a traditional safety net to prevent large losses
    # on a trade that moves against you.
    stop_loss:
        type: 'percentage'
        value: 7.0 # Sell if the position loses 5% of its value.



strategies:
    - name: 'MomentumStrategy'
      params:
          momentum_window: 5
    - name: 'Momentum2Strategy'
      params:
          momentum_window: 15
    - name: 'SmaRsiStrategy'
      params:
          short_window: 10
          long_window: 20
          rsi_period: 14
          rsi_threshold: 75
    - name: 'SmaRsi2Strategy'
      params:
          short_window: 20
          long_window: 50
          rsi_period: 14
          rsi_threshold: 75
    - name: 'KeltnerStrategy'
      params:
          ema_period: 30
          atr_period: 15
          atr_multiplier: 2.0
    - name: 'BollingerRsiStrategy'
      params:
          bband_period: 20
          bband_std_dev: 2.0
          rsi_period: 14
          rsi_buy_threshold: 70
          rsi_sell_threshold: 30
    - name: 'MacdStrategy'
      params:
          short_ema_period: 12
          long_ema_period: 26
          signal_ema_period: 9



tickers:
- 'spy'
- 'aapl'
- 'abbv'
- 'abt'
- 'adbe'
- 'adi'
- 'afl'
- 'aig'
- 'all'
- 'amd'
- 'amgn'
- 'amzn'
- 'aon'
- 'axp'
- 'ba'
- 'bac'
- 'bkng'
- 'blk'
- 'bmy'
- 'c'
- 'cat'
- 'cb'
- 'chd'
- 'ci'
- 'cl'
- 'cmcsa'
- 'cnc'
- 'cop'
- 'cost'
- 'crm'
- 'csco'
- 'cvx'
- 'dal'
- 'dhr'
- 'dis'
- 'ea'
- 'ecl'
- 'ed'
- 'emr'
- 'eog'
- 'eqix'
- 'exc'
- 'expd'
- 'f'
- 'fcx'
- 'fdx'
- 'fis'
- 'gd'
- 'ge'
- 'gild'
- 'goog'
- 'googl'
- 'gpn'
- 'gs'
- 'hca'
- 'hd'
- 'hon'
- 'hpe'
- 'hpq'
- 'hum'
- 'ibm'
- 'ice'
- 'iff'
- 'ilmn'
- 'intc'
- 'intu'
- 'isrg'
- 'itw'
- 'jnj'
- 'jpm'
- 'k'
- 'kdp'
- 'key'
- 'khc'
- 'kmb'
- 'kmi'
- 'ko'
- 'lin'
- 'lly'
- 'lmt'
- 'low'
- 'lrcx'
- 'ma'
- 'mas'
- 'mcd'
- 'mck'
- 'mco'
- 'mdlz'
- 'met'
- 'meta'
- 'mmc'
- 'mrk'
- 'mrna'
- 'ms'
- 'msft'
- 'mu'
- 'ndaq'
- 'nem'
- 'nflx'
- 'nke'
- 'nvda'
- 'o'
- 'orcl'
- 'oxy'
- 'pep'
- 'pfe'
- 'pg'
- 'pgr'
- 'pld'
- 'pm'
- 'pnc'
- 'ppg'
- 'psx'
- 'pypl'
- 'qcom'
- 'regn'
- 'rop'
- 'rtx'
- 'sbux'
- 'shw'
- 'slb'
- 'sna'
- 'so'
- 'spg'
- 'sre'
- 'stt'
- 'stz'
- 'syk'
- 'tdg'
- 'tdy'
- 'tmo'
- 'tmus'
- 'trv'
- 'tsla'
- 'txn'
- 'unh'
- 'unp'
- 'ups'
- 'usb'
- 'v'
- 'vfc'
- 'vrtx'
- 'vz'
- 'wday'
- 'wfc'
- 'wm'
- 'wmt'
- 'wst'
- 'xom'
- 'yum'
- 'zts'
    # ... add all other tickers here ...


          